"""The colours release: bend each change back one at a time and see a test fail.

Each mutation puts back (or breaks) one thing the release did, runs the tests
that should notice, expects a failure, and restores the file exactly. Run on the
finished tree: `python -X utf8 k13_mutate.py`. Prints one line per mutation and
MUTATIONS_CAUGHT n of m."""
import subprocess
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2] / "plugins" / "lesson-v4"
print(f"mutating (and restoring) files in {ROOT}")

BUILDER = ["node", "--test", "test/colours-follow-the-board.test.js", "test/slide-design-check.test.js",
           "test/doc-claims.test.js", "test/header-instruction.test.js"]
SHEET = ["node", "--test", "test/worked-example-purple.test.js", "test/tokens.test.js", "test/helpers.test.js",
         "test/figure-words-plain.test.js"]
STICKIN = ["node", "--test", "test/figure-words-plain.test.js"]
WALL = ["node", "--test", "test/colours-follow-the-board.test.js"]
PY = ["python", "-X", "utf8", "-m", "pytest", "scripts/tests/test_colours_are_kept.py", "-q", "-p", "no:cacheprovider"]

MUTATIONS = [
    ("the task-blue role is not a role", "builder/src/presentation-text.js",
     "  'task-blue',\n", "", "builder", BUILDER),
    ("a task-blue line is drawn black", "builder/src/presentation-text.js",
     "  if (role === 'task-blue') return COLOURS.title;\n", "  if (role === 'task-blue') return COLOURS.body;\n",
     "builder", BUILDER),
    ("a marked short task is refused like any blue line", "builder/scripts/check-slide-design.js",
     "  if (nodeIsBlue(node) && node.colorRole !== 'task-blue' && typeof whole === 'string') {\n",
     "  if (nodeIsBlue(node) && typeof whole === 'string') {\n", "builder", BUILDER),
    ("a task-blue line may carry an answer", "builder/scripts/check-slide-design.js",
     "  if (TASK_BLUE_REVEAL.test(whole)) {\n", "  if (false) {\n", "builder", BUILDER),
    ("a task-blue line may hold several instructions", "builder/scripts/check-slide-design.js",
     "  if (tasks.length > 1) {\n", "  if (tasks.length > 9) {\n", "builder", BUILDER),
    ("the header cue turns blue again", "builder/src/headers.js",
     "      color: COLOURS.body, align: textX ? 'left' : 'right', valign: 'middle',\n      margin: 0, fit: FIT\n    });\n  }\n}\n\nfunction drawStarterHeader",
     "      color: COLOURS.title, align: textX ? 'left' : 'right', valign: 'middle',\n      margin: 0, fit: FIT\n    });\n  }\n}\n\nfunction drawStarterHeader",
     "builder", BUILDER),
    ("a worked line is drawn in peer purple's place, not the worked colour", "builder/src/presentation-text.js",
     "  if (role === 'worked-purple') return COLOURS.worked;\n", "  if (role === 'worked-purple') return COLOURS.body;\n",
     "builder", BUILDER),
    ("a worked place-value row prints black", "shared/visuals/place-value-chart-svg.js",
     "fill: worked ? pal.worked : (picked || revealed) ? pal.ring : pal.text, picked });",
     "fill: (picked || revealed) ? pal.ring : pal.text, picked });", "builder", BUILDER),
    ("a worked row's ringed digit prints green again", "shared/visuals/place-value-chart-svg.js",
     "fill: worked ? pal.worked : (picked || revealed) ? pal.ring : pal.text, picked });",
     "fill: (picked || revealed) ? pal.ring : worked ? pal.worked : pal.text, picked });", "builder", BUILDER),
    ("a worked row prints purple on the photocopied stick-in pack", "shared/visuals/place-value-chart-svg.js",
     "  worked: '#1A1A1A',\n", "  worked: '#7030A0',\n", "builder", BUILDER),
    ("prepared examples stay black again in preferences", "references/preferences.md",
     "Prepared examples and `visible-in-unit` models are worked examples, finished before the class sees them, so they are purple, the same colour as a sticky fact, never answer green.",
     "Prepared examples and `visible-in-unit` models are teaching content and stay black, even when they are complete.",
     ".", PY),
    ("the profile's action-role line says blue belongs to questions again", "references/teacher-slide-visual-profile.md",
     "never blue on its own, because blue belongs to the child's job as a whole line, a question or a short task (Semantic colour below).",
     "never blue, because blue belongs to questions (Semantic colour below).", ".", PY),
    ("the playbook's action-role line says blue stays the question's again", "references/slide-composition-playbook.md",
     "blue stays with the child's job as a whole line, the question or the short task.", "blue stays the question's.", ".", PY),
    ("the catalogue's method-frame title is green again", "references/templates.md",
     "- `title` — optional purple heading above the lines", "- `title` — optional green heading above the lines", ".", PY),
    ("the sticky card's panel is pale blue again", "working-wall-html/style.json",
     '"stickyPanelFill": "EDE3F5",', '"stickyPanelFill": "DEEAF1",', "working-wall-html", WALL),
    ("the stem's bullet is green again", "working-wall-html/style.json",
     '"sentenceStemBullet": "000000",', '"sentenceStemBullet": "00B050",', "working-wall-html", WALL),
    ("the callout's default is blue, not the statement's black", "builder/src/content/callout.js",
     "const DEFAULT_VARIANT = 'black';", "const DEFAULT_VARIANT = 'blue';", "builder", BUILDER),
    ("a taught chip prints in the variant's colour", "builder/src/content/chip-bank.js",
     "color: c.taught ? COLOURS.green : variant.text,", "color: variant.text,", "builder", BUILDER),
    ("a taught chip keeps its braces", "builder/src/content/chip-bank.js",
     "    ? { label: match[1].trim(), taught: true }", "    ? { label: text, taught: true }", "builder", BUILDER),
    ("the method frame's edge is green again", "builder/src/content/method-frame.js",
     "const PANEL_LINE      = COLOURS.worked;", "const PANEL_LINE      = '00B050';", "builder", BUILDER),
    ("the method frame's title is green again", "builder/src/content/method-frame.js",
     "const TITLE_COLOUR    = COLOURS.worked;", "const TITLE_COLOUR    = '00B050';", "builder", BUILDER),
    ("a worked frame's edge on the sheet is ink", "worksheet-html/src/helpers/methods.js",
     "  .h-mframe-framed.h-mframe-worked { border-color: var(--colour-worked); }",
     "  .h-mframe-framed.h-mframe-worked { border-color: var(--colour-ink); }", "worksheet-html", SHEET),
    ("a worked frame's title on the sheet is question blue", "worksheet-html/src/helpers/methods.js",
     "  .h-mframe-worked .h-mframe-title { color: var(--colour-worked); }",
     "  .h-mframe-worked .h-mframe-title { color: var(--colour-question); }", "worksheet-html", SHEET),
    ("the sticky card is navy again", "working-wall-html/style.json",
     '"stickyTitleBarFill": "7030A0",', '"stickyTitleBarFill": "1F4E79",', "working-wall-html", WALL),
    ("the vocabulary card is teal again", "working-wall-html/style.json",
     '"vocabDefinitionTitleBarFill": "00B050",', '"vocabDefinitionTitleBarFill": "0D9488",', "working-wall-html", WALL),
    ("the stem's modelled line is green again", "working-wall-html/style.json",
     '"sentenceStemLabel": "7030A0",', '"sentenceStemLabel": "00B050",', "working-wall-html", WALL),
    ("a section part is teal again", "working-wall-html/src/render-section.js",
     '{ strip: "E46C0A", fill: "FEF4EB", accent: "E46C0A" },', '{ strip: "0D9488", fill: "F0FDFA", accent: "0D9488" },',
     "working-wall-html", WALL),
    ("a part's answer takes the part's colour", "working-wall-html/src/render-section.js",
     "background:${hash(item.worked ? RESULT_WORKED : RESULT_GREEN)};", "background:${hash(theme.strip)};",
     "working-wall-html", WALL),
    ("a worked part's result is answer green", "working-wall-html/src/render-section.js",
     'const RESULT_WORKED = "7030A0";', 'const RESULT_WORKED = "00B050";', "working-wall-html", WALL),
    ("a fourth part is green again", "working-wall-html/src/render-section.js",
     '  { strip: "7030A0", fill: "F4EEF9", accent: "7030A0" },\n];',
     '  { strip: "7030A0", fill: "F4EEF9", accent: "7030A0" },\n  { strip: "00B050", fill: "F1FBF4", accent: "00873E" },\n];',
     "working-wall-html", WALL),
    ("a stem draws no taught word green", "working-wall-html/src/render-panels.js",
     "`<span style=\"color:${hash(style.colours.body)};\">${markedHtml(text)}</span>` +",
     "`<span style=\"color:${hash(style.colours.body)};\">${esc(text)}</span>` +", "working-wall-html", WALL),
    ("a table cell prints its marks as braces", "working-wall-html/src/render-grids.js",
     "color:${hash(textColour)};\">${markedHtml(cell)}</div>`;", "color:${hash(textColour)};\">${esc(cell)}</div>`;",
     "working-wall-html", WALL),
    ("a section note prints its marks as braces", "working-wall-html/src/render-section.js",
     "padding:${mm(0.02)}mm 0;\">${markedHtml(item.text)}</div>`;", "padding:${mm(0.02)}mm 0;\">${esc(item.text)}</div>`;",
     "working-wall-html", WALL),
    ("the big idea is teal again", "working-wall-html/src/render-overview.js",
     "{ color: style.colours.stickyPanelLine }) +\n    overviewTextHtml(card.keySentence",
     "{ color: \"0D9488\" }) +\n    overviewTextHtml(card.keySentence", "working-wall-html", WALL),
    ("the second group is teal again", "working-wall-html/src/render-overview.js",
     'idx === 0 ? "0070C0" : "E46C0A"', 'idx === 0 ? "0070C0" : "0D9488"', "working-wall-html", WALL),
    ("the labelled diagram borrows the worked example's colour", "working-wall-html/src/render-display.js",
     "style.colours.labelledDiagramTitleBarFill", "style.colours.workedExampleTitleBarFill", "working-wall-html", WALL),
    ("preferences loses his words", "references/preferences.md",
     "I want blue means question or like a short task", "I want blue for questions", ".", PY),
    ("the profile brings back \"a task is black either way\"", "references/teacher-slide-visual-profile.md",
     "The limit is what keeps blue meaning something:", "A task is black either way. The limit is what keeps blue meaning something:",
     ".", PY),
    ("the profile counts words again", "references/teacher-slide-visual-profile.md",
     "The check reads the role, not the words:", "The check counts five words or fewer, not the role:", ".", PY),
]

# The second check's repairs, and the attacks that got through it.
MUTATIONS += [
    ("the role makes a turn again", "builder/scripts/check-slide-design.js",
     "    else if (node.colorRole === 'task-blue' && taskBlueAsks(node)) found = true;\n",
     "    else if (node.colorRole === 'task-blue') found = true;\n", "builder", BUILDER),
    ("a taught word is refused on a task-blue line", "builder/scripts/check-slide-design.js",
     "const TASK_BLUE_REVEAL = /\\|\\|/;", "const TASK_BLUE_REVEAL = /\\|\\||\\{\\{/;", "builder", BUILDER),
    ("a starter of task-blue lines is not seen as blue", "builder/scripts/check-slide-design.js",
     "    node.colorRole === 'task-blue' ||\n", "", "builder", BUILDER),
    ("a sticky fact the design names passes as a task", "builder/scripts/check-slide-design.js",
     "|| facts.sticky.has(plainLine(whole))) {", ") {", "builder", BUILDER),
    ("the design's answer passes as a task", "builder/scripts/check-slide-design.js",
     "  if (facts.answers.has(plainLine(whole))) {\n", "  if (false) {\n", "builder", BUILDER),
    ("a tell-then-ask line passes as a task", "builder/scripts/check-slide-design.js",
     "  if (tasks.length === 1 && sentences[sentences.length - 1].endsWith('?')) {\n", "  if (false) {\n",
     "builder", BUILDER),
    ("e.g. ends a sentence again", "builder/scripts/check-slide-design.js",
     "  return splitSentences(String(whole).replace(/\\b(e\\.g|i\\.e)\\.(?=\\s)/gi, (m) => m.replace(/\\./g, '\u2024')));\n",
     "  return splitSentences(String(whole));\n", "builder", BUILDER),
    ("the verb list loses the saved decks' say", "builder/scripts/check-slide-design.js",
     "'record', 'round', 'say', 'shade',", "'record', 'round', 'shade',", "builder", BUILDER),
    ("place value opens a task", "builder/scripts/check-slide-design.js",
     "'pick', 'place(?! value)', 'plan',", "'pick', 'place', 'plan',", "builder", BUILDER),
    ("the blue message loses what stays black", "builder/scripts/check-slide-design.js",
     "            'an answer or an instruction about how to go about the task is ' +\n", "", "builder", BUILDER),
    ("the turn message loses what task-blue is for", "builder/scripts/check-slide-design.js",
     "        'only for the child\\'s own short task, the job itself (`Explain your ' +\n", "", "builder", BUILDER),
    ("the task-blue message loses its repair", "builder/scripts/check-slide-design.js",
     "          'give each short task its own line and each question its own line ' +\n", "", "builder", BUILDER),
    ("a teach layout refuses worked-purple again", "builder/src/teach-layouts.js",
     "      .filter((k) => !(k === 'colorRole' && value.colorRole === 'worked-purple'));\n", ";\n",
     "builder", BUILDER),
    ("a teach layout takes the role and draws it black", "builder/src/teach-layouts.js",
     "  else if (slot.worked) out.colorRole = 'worked-purple';\n", "", "builder", BUILDER),
    ("a teach layout's question takes worked-purple", "builder/src/teach-layouts.js",
     "  if (item.worked && (role === 'question' || role === 'sticky')) {\n", "  if (false) {\n", "builder", BUILDER),
    ("a worked step prints black", "builder/src/content/steps.js",
     "      color: step.worked ? COLOURS.worked : COLOURS.body,\n", "      color: COLOURS.body,\n", "builder", BUILDER),
    ("a worked step's number stays green", "builder/src/content/steps.js",
     "    const badgeColour = step.worked ? COLOURS.worked : COLOURS.green;\n",
     "    const badgeColour = COLOURS.green;\n", "builder", BUILDER),
    ("any role on a step passes and prints black", "builder/src/validate.js",
     "      if (step.colorRole === 'worked-purple') return;\n", "      return;\n", "builder", BUILDER),
    ("the method frame's pale ground is pale green", "builder/src/styles.js",
     "  workedBg:    'EDE3F5',\n", "  workedBg:    'E8F6EE',\n", "builder", BUILDER),
    ("the wall prints a taught word's braces", "working-wall-html/src/shared.js",
     "    .replace(TAUGHT_MARK, \"$1\")\n", "", "working-wall-html", WALL),
    ("a sticky fact draws no taught word green", "working-wall-html/src/render-panels.js",
     "font-size:${pt}pt;color:${hash(style.colours.body)};\">${markedHtml(text)}</div>`",
     "font-size:${pt}pt;color:${hash(style.colours.body)};\">${esc(text)}</div>`", "working-wall-html", WALL),
    ("a sticky fact measures its marks", "working-wall-html/src/render-panels.js",
     "  const items = shown.map((item) => ({ ...item, text: plainCriteria(item.text) }));\n",
     "  const items = shown;\n", "working-wall-html", WALL),
    ("a definition measures its marks", "working-wall-html/src/render-panels.js",
     "[{ text: plainCriteria(definition) }]", "[{ text: definition }]", "working-wall-html", WALL),
    ("a misconception measures its marks", "working-wall-html/src/render-panels.js",
     "  const fitItems = items.length > 0 ? items.map((item) => ({ ...item, text: plainCriteria(item.text) })) : [{ text: \"\" }];\n",
     "  const fitItems = items.length > 0 ? items : [{ text: \"\" }];\n", "working-wall-html", WALL),
    ("a stem measures its marks", "working-wall-html/src/render-panels.js",
     "    fitItems.push({ text: plainCriteria(item.text) });\n", "    fitItems.push({ text: item.text });\n",
     "working-wall-html", WALL),
    ("a table cell measures its marks", "working-wall-html/src/render-grids.js",
     "? \"\" : plainCriteria(cell))", "? \"\" : cell)", "working-wall-html", WALL),
    ("a section note measures its marks", "working-wall-html/src/render-section.js",
     "fitLinearBodySize(items.map((item) => ({ ...item, text: plainCriteria(item.text) })), NOTE_PT,",
     "fitLinearBodySize(items, NOTE_PT,", "working-wall-html", WALL),
    ("the map caption is blue again", "working-wall-html/src/render-overview.js",
     "    overviewTextHtml(card.map.caption || \"\", 25, style);\n",
     "    overviewTextHtml(card.map.caption || \"\", 25, style, { color: style.colours.referenceTableHeaderFill });\n",
     "working-wall-html", WALL),
    ("the map sits on pale blue again", "working-wall-html/src/render-overview.js",
     "    fillColour: \"F4F6FA\",\n", "    fillColour: \"DEEAF1\",\n", "working-wall-html", WALL),
    ("the contracts' list of where marks carry over loses a table cell", "references/working-wall-card-contracts.md",
     "a sentence stem, a reference-table cell and a section's notes", "a sentence stem and a section's notes",
     ".", PY),
    ("paragraph rhythm blackens every instruction", "references/teacher-slide-visual-profile.md",
     "and a question or a short task takes its blue per Semantic colour",
     "and a question takes its blue per Semantic colour while every instruction stays black", ".", PY),
    ("the speech-bubble rule names no role", "references/slide-speech-and-characters.md",
     "in question blue as the child's short task (`colorRole: \"task-blue\"`).", "in question blue.", ".", PY),
    ("a sheet comment counts four colour meanings again", "worksheet-html/src/helpers/frames.js",
     "keeps scaffold from becoming a colour meaning of its own. A word bank IS",
     "keeps the page to four colour meanings instead of five. A word bank IS", ".", PY),
    ("the profile says purple reaches everything", "references/teacher-slide-visual-profile.md",
     " Purple does not reach a figure with no purple of its own (a number line, a bar model, a tally, a table's cells), a worksheet's first worked row, or the good card of a strong-and-weak pair: those keep their own colours.",
     "", ".", PY),
    # His answer of 25 September 2026: a job that names what to use is blue.
    ("the profile loses his job-with-its-how example", "references/teacher-slide-visual-profile.md",
     "A job that also names what to use is still the job, and blue: `Explain your answer using the photograph.` and `Describe each tooth using the pictures.` (the teacher's answer, 25 September 2026). ",
     "", ".", PY),
    # His answers of 25 September 2026: "1. yes 2. leave it 3. yes".
    ("the ring on a worked row is green again", "shared/visuals/place-value-chart-svg.js",
     "          const ringStroke = row.worked && !row.answer ? pal.worked : pal.ring;\n",
     "          const ringStroke = pal.ring;\n", "builder", BUILDER),
    ("the drawing paints every ring green", "shared/visuals/place-value-chart-svg.js",
     "stroke=\"${r.stroke || L.pal.ring}\"", "stroke=\"${L.pal.ring}\"", "builder", BUILDER),
    ("an empty sheet frame is purple", "worksheet-html/src/helpers/methods.js",
     "    return !segs.some((s) => s.box) && segs.some((s) => /\\d/.test(s.text));\n", "    return true;\n", "worksheet-html", SHEET),
    # The fourth check's repairs.
    ("a line of words makes a frame purple", "worksheet-html/src/helpers/methods.js",
     "    return !segs.some((s) => s.box) && segs.some((s) => /\\d/.test(s.text));\n",
     "    return segs.length > 0 && !segs.some((s) => s.box);\n", "worksheet-html", SHEET),
    ("a marked worked step prints black", "builder/src/content/steps.js",
     "splitAnswerRuns(step.text, true, step.worked ? COLOURS.worked : undefined)",
     "splitAnswerRuns(step.text, true)", "builder", BUILDER),
    ("the hex refusal says to take the role off", "builder/scripts/check-slide-design.js",
     "'hex: take the `color` off and keep `colorRole: \"task-blue\"`. If the line is not the ' +",
     "'hex: take the role off. If the line is not the ' +", "builder", BUILDER),
    ("a Teach step takes an extra field", "builder/src/teach-layouts.js",
     "if (typeof words !== 'string' || !words.trim() || extra.length || v.colorRole !== 'worked-purple') {",
     "if (typeof words !== 'string' || !words.trim() || v.colorRole !== 'worked-purple') {", "builder", BUILDER),
    ("the shared helper takes off only the first mark", "shared/text/criteria-marks.js",
     "const TAUGHT_MARK = /\\{\\{([\\s\\S]+?)\\}\\}/g;", "const TAUGHT_MARK = /\\{\\{([\\s\\S]+?)\\}\\}/;", "builder", BUILDER),
    ("the stick-in caption prints a label's braces", "stick-in-sheets-html/build.js",
     "  const captionText = withoutTaughtMarks(moments.length === 1\n", "  const captionText = (moments.length === 1\n",
     "stick-in-sheets-html", STICKIN),
    ("a worked sheet frame is not purple", "worksheet-html/src/helpers/methods.js",
     "${worked ? \" h-mframe-worked\" : \"\"}", "", "worksheet-html", SHEET),
    ("an empty sheet frame's edge is purple", "worksheet-html/src/helpers/methods.js",
     "    border: var(--rule-line) solid var(--colour-ink);\n    box-sizing: border-box;\n  }\n  .h-mframe-title {",
     "    border: var(--rule-line) solid var(--colour-worked);\n    box-sizing: border-box;\n  }\n  .h-mframe-title {",
     "worksheet-html", SHEET),
    ("the profile says an empty sheet frame is purple too", "references/teacher-slide-visual-profile.md",
     " when it shows worked numbers; an empty one, the child's to fill in every box, keeps its ink edge and blue heading.",
     ".", ".", PY),
    ("the catalogue calls a job with its how advice", "references/templates.md",
     "same line, and a job that also names what to use (`Explain your answer using the photograph.`), taking its blue",
     "same line; advice (`Explain your answer using the photograph.`), taking its blue", ".", PY),
    # The third check's repairs.
    ("a task-blue line may carry its own colour", "builder/scripts/check-slide-design.js",
     "      const ownColour = [node.color, node.colour].find((c) => typeof c === 'string' && c.trim());\n",
     "      const ownColour = null;\n", "builder", BUILDER),
    ("a Teach slide's worked step is refused", "builder/src/teach-layouts.js",
     "      if (v && typeof v === 'object' && !Array.isArray(v)) {\n        const words",
     "      if (false) {\n        const words", "builder", BUILDER),
    ("a Teach slide's worked step drops its role", "builder/src/teach-layouts.js",
     "        return { text: words, colorRole: 'worked-purple' };\n", "        return words;\n", "builder", BUILDER),
    # A taught word's braces never print from a figure (the third check, item 2).
    ("the shared helper keeps a taught word's braces", "shared/text/criteria-marks.js",
     "  if (typeof value === 'string') return value.replace(TAUGHT_MARK, '$1');\n",
     "  if (typeof value === 'string') return value;\n", "builder", BUILDER),
    ("the board draws a figure's braces", "builder/src/figure-marks.js",
     "    const plain = withoutTaughtMarks(node);\n", "    const plain = node;\n", "builder", BUILDER),
    ("the board's caption loses its green", "builder/src/figure-marks.js",
     "      return Object.assign({}, plain, { label: node.label });\n", "      return plain;\n", "builder", BUILDER),
    ("the board's build never takes the braces off", "builder/build.js",
     "  const coreLesson = withoutFigureMarks(withoutDecorations(lesson));\n",
     "  const coreLesson = withoutDecorations(lesson);\n", "builder", BUILDER),
    ("the sheet hands a figure its braces", "worksheet-html/src/helpers/index.js",
     "REGISTRY[name] = withLegibilityFloor(FIGURE_HELPERS.has(name) ? withPlainFigureWords(helper) : helper);",
     "REGISTRY[name] = withLegibilityFloor(helper);", "worksheet-html", SHEET),
    ("the wall's pre-render draws a figure's braces", "working-wall-html/src/svg-renderer.js",
     "    const visual = withoutTaughtMarks(marked);\n", "    const visual = marked;\n", "working-wall-html", WALL),
    ("the wall's card lookup keys a figure with its braces", "working-wall-html/src/visuals.js",
     "  const visual = withoutTaughtMarks(marked);\n", "  const visual = marked;\n", "working-wall-html", WALL),
    ("the stick-in pack draws a figure's braces", "stick-in-sheets-html/src/render-piece-html.js",
     "  const item = withoutTaughtMarks(marked);\n", "  const item = marked;\n", "stick-in-sheets-html", STICKIN),
    # The build log's own claims (the third check's D14 got through).
    ("the log's refusal sentence says it refuses an answer", "references/build-review-log.md",
     "and refuses a `task-blue` line the spec shows is not a short task (`TASK_BLUE_NOT_A_SHORT_TASK`):",
     "and refuses a `task-blue` line that carries an answer (`TASK_BLUE_NOT_A_SHORT_TASK`):", ".", PY),
    ("the log says a figure's braces print nowhere", "references/build-review-log.md",
     "A taught word's braces never print on any card or from any figure: a title, a coloured strip and a figure's own words",
     "A taught word's braces print nowhere: a title, a coloured strip and a figure's own words", ".", PY),
    ("an extract takes worked-purple and prints black", "builder/src/teach-layouts.js",
     "  if (item.worked && role === 'extract') {\n", "  if (false) {\n", "builder", BUILDER),
]

caught = 0
for name, rel, old, new, cwd, command in MUTATIONS:
    path = ROOT / rel
    original = path.read_bytes()
    text = original.decode("utf-8")
    old_eol = old.replace("\n", "\r\n") if "\r\n" in text else old
    new_eol = new.replace("\n", "\r\n") if "\r\n" in text else new
    assert text.count(old_eol) == 1, (name, text.count(old_eol))
    try:
        path.write_bytes(text.replace(old_eol, new_eol).encode("utf-8"))
        run = subprocess.run(command, cwd=ROOT / cwd if cwd != "." else ROOT, capture_output=True, text=True,
                             encoding="utf-8", errors="replace")
        failed = run.returncode != 0
    finally:
        path.write_bytes(original)
    caught += failed
    print(f"{'caught ' if failed else 'MISSED '} {name}")
print(f"MUTATIONS_CAUGHT {caught} of {len(MUTATIONS)}")
