"""The colours release, step 9: the build-log entry, written above the stories
`k1_stories_first.py` copied there first. No version number: the lead numbers
the release at merge (and bumps both plugin.json files then)."""
from _patch import LOG, read, replace_once

HEADING = ("## 2026-09-25 - Blue is a question or a short task, green a taught word or an answer, and a "
           "worked example is purple on the board, the sheet and the wall\n"
           "\n"
           "*Topic 7's 7C in `plans/2026-09-24-topic-7-change-plan.md`: colours.*\n"
           "\n")
assert read(LOG).count(HEADING) == 1
assert "- **His answers.** Decision 11 on the rest-of-preferences list" not in read(LOG)

BODY = (
    "- **His answers.** Decision 11 on the rest-of-preferences list (24 September 2026): \"I want blue means "
    "question or like a short task as in like explain why or something like that. And yeah, green is "
    "vocabulary or an answer. So we'd have to fix those. Worked examples can be something different. Maybe "
    "purple.\", then \"worked example purple too\"; the change plan's question 1, \"yes\": a question or a short "
    "task is blue, and a longer instruction about how to go about it stays black. Decision 22, its colour "
    "half, \"yes\": the working wall uses the board's colour meanings. Told he had greened a mistaken worked "
    "chain himself on 19 September: \"purple is fine\". Asked on 25 September whether a job with its how in "
    "one line, `Explain your answer using the photograph.`, is blue: \"y\". Shown three details the repairs "
    "left (the ring on a worked row, a wall section's purple third part, an empty method frame on a sheet): "
    "\"1. yes 2. leave it 3. yes\". Built on a side branch beside 7A and 7B.\n"
    "- **Blue.** A short task is the child's job (`Explain your answer.`, `Write one reason.`, `Round 346 to "
    "the nearest 10.`), and a job that names what to use is still the job (`Explain your answer using the "
    "photograph.`, `Describe each tooth using the pictures.`); a line that only says how to go about it "
    "(`Use the shaded map.`, `Use the two photographs.`) is not, and the line he answered no longer stands as "
    "a black example anywhere. No count of words tells "
    "them apart, and the lesson design has no field that does, so the slide designer says which with a new "
    "colour role, `task-blue`, drawn in house blue, and the check reads the role. It refuses every other blue "
    "line that asks nothing, as 4.2.289 did (`BLUE_WITHOUT_A_QUESTION`, its message rewritten), and refuses a "
    "`task-blue` line the spec shows is not a short task (`TASK_BLUE_NOT_A_SHORT_TASK`): one carrying the reveal "
    "mark `||`, a sticky fact (by its sparkle, or the lesson design's own words), the design's answer, a "
    "statement or a task before a question, two sentences that are not questions, or a colour of its own "
    "beside the role (a hex beside it had let a statement count as the turn; the message says to take the "
    "colour off and keep the role). A lone statement or a "
    "piece of advice marked `task-blue` still passes that rule, which cannot read meaning, but the role never "
    "makes a slide's turn: a marked line counts by its words, a question in it or an opening task verb, and "
    "the verb list gains the openers the saved decks use (say, justify, put, take, place but not place value, "
    "suggest, imagine, ask, plan, improve). The speech-bubble rule's leftover task line names the role, and "
    "the profile's paragraph rhythm gives a short task its blue. The header's small cue stays "
    "black: it is advice, and the profile now says so. The visual profile's Semantic colour is the one home: "
    "preferences' three blue paragraphs folded into it (the peer line gained \"answer status\", the stale "
    "\"task-action verbs may use house blue\" went) and preferences keeps his words and a pointer naming "
    "every part the profile owns. The playbook, the catalogue's colour lines and the two places that still "
    "said \"blue belongs to questions\" follow. His own job line of 18 September (`Explain how Sam's tooth "
    "decayed.`, left open in this log) is right now, once marked `task-blue`.\n"
    "- **Green.** The catalogue's exceptions he was shown are corrected: a word inside a statement stays "
    "black (`The tens column changes.`); a table's deciding word is bold, not blue, and the catalogue says "
    "bold shows nothing in the first column or in a callout, which are bold throughout; a callout's default "
    "edge is black, a statement's colour, blue marks a question, and green is no longer a callout colour (a "
    "spec that names it gets the default); a chip written `{{word}}` is a taught word and prints green, "
    "braces never printed. Two out-of-date colour words and two code comments that gave the old rule are "
    "corrected.\n"
    "- **Purple.** A worked example is purple wherever his answer reaches. A prepared example and a "
    "`visible-in-unit` model are worked examples (preferences said they \"stay black\"; the contract, the slide "
    "designer, the playbook and the catalogue said so too), so their lines take a new role, `worked-purple`, "
    "in the sticky purple, on any slide: a teach layout, where 16 of the 17 saved models the class sees "
    "finished sit, refused every colour role and now takes this one on an explanation line and on a step of "
    "its `steps` and `picture-steps` layouts; a step list draws it on a step's words and number (a taught or "
    "bold word in a worked step keeps the rest of it purple) and refuses "
    "any other role on a step, where it had drawn every step black; a source's extract refuses it, saying "
    "why, where it had taken it and printed black. A place-value chart row takes `worked: true`, a mistaken worked chain included, and every "
    "digit on it is purple, the ringed one and its ring too (his \"1. yes\"). "
    "The board's `method-frame` draws its panel and title purple, and the sheet's twin its edge and title "
    "when it shows worked numbers, one line or more whose values are worked right through (a line of words "
    "alone decides nothing; his \"3. yes\": a frame the child "
    "fills in every box keeps its ink edge and blue heading, as before) "
    "(a fifth colour on paper, on the frame's edge and its title, which is words a child reads; what a child "
    "writes, and the frame's labels, stay ink). The profile says where purple does not reach: a figure with "
    "no purple of its own, a worksheet's first worked row, the good card of a strong-and-weak pair. The "
    "success-criteria panel's green is unchanged. No saved deck or sheet uses a method frame, a callout or "
    "either new role, so all of this shows first in new lessons.\n"
    "- **The wall.** `style.json`: the sticky fact and the worked example purple, vocabulary green (not teal), a "
    "misconception's red and green under a blue title, every other title bar and the table header blue, the "
    "sentence stem neutral with its modelled line purple. The diagram section's parts take the board's "
    "category colours (blue, orange, purple); a part's right answer sits on a green strip, and a part marked "
    "`worked: true`, a worked example, a mistaken one included, shows its result on purple; a third part keeps "
    "the board's category purple (his \"2. leave it\"); the overview sheets "
    "lose teal and navy (a blue and orange pair of groups, a purple big idea and cause-card reason, black "
    "captions). The board's colour marks now draw on a sentence stem, a table cell, a section's notes and "
    "steps, a sticky fact, a definition, a misconception and a worked example's lines, measured without the "
    "marks. A taught word's braces never print on any card or from any figure: a title, a coloured strip and "
    "a figure's own words (a labelled diagram's labels, a Venn's items) print the word plain. A figure's words "
    "are drawn into its picture by a shared drawing, which printed `{{enamel}}` as written on every surface, "
    "so one shared helper takes the braces off wherever the board, the sheet, the wall and the stick-in pack "
    "hand a figure to a shared drawing (the lead's choice, by his standing rule that a stray mark never stops "
    "a build); a caption the board sets as text under a figure keeps its mark and its green. The stick-in "
    "pack's page caption and handles print the word plain too. The zoners' and "
    "banners' rainbow and the shared figures' colours are unchanged. Because the sticky and worked-example cards now share purple, the wall's words say a child "
    "tells fact from method by the card's shape.\n"
    "- **Pinned.** A pin file of its own, `scripts/tests/colours_ledger_pins.json` with "
    "`test_colours_are_kept.py`, because the rest-of-preferences list has none yet (7B's takes these rows from "
    "the release's builder): 40 ledger rows (36 from the rest of preferences, 4 from the starters list), eight "
    "added mechanisms (every wall colour the mapping decided pinned as a value), the retired wordings barred, "
    "and the profile's Semantic colour pinned paragraph by paragraph. Five success-criteria pins followed "
    "their words (SC-J11, SC-J12, SC-O15, SC-O23, SC-O28).\n"
    "- **Checked.** Every suite passes. Each of 101 changes, bent back one at a time, is caught by a test, "
    "among them what got through the second check (the three refusal messages' guidance, the role's turn, "
    "the method frame's pale ground, a worked row on the stick-in pack, the wall's measuring with marks, a "
    "fourth section part, the map's caption and ground, the contracts' list and the paragraph rhythm line) "
    "and the third (a hex beside the role, a Teach slide's worked steps, an extract, and a figure's braces on "
    "each of the four surfaces, each test reading the drawn picture's own text) and the fourth (a worked step "
    "carrying a mark, a Teach step's extra field, two marks in one string, the hex message, a frame line of "
    "words, the stick-in caption). "
    "The saved lines the checks named were run both ways: every job line passes once marked, and every "
    "advice line, statement and label painted blue without the role is refused. The saved designs give the "
    "same results (the design check is untouched). A first build counted words (five or fewer); its first "
    "check found that refused 41 saved job lines and passed how-to lines and statements, and it was replaced "
    "by the role before anything was committed.\n"
    "- **Size, honestly.** The instruction files are about 7.8 KB larger: preferences lost 0.4 KB to the "
    "fold, and the profile, the catalogue and the wall files carry the corrections, the two new roles, where "
    "purple reaches and his examples. The programs are about 24 KB larger, most of it the short-task "
    "check, the wall's colour marks, purple on a teach layout and a step list, and the four surfaces taking "
    "a figure's braces off.\n"
    "- **Not done.** Untried on a real run. The rendered pages he has not yet seen: "
    "`plans/streamline-tools/colours-renders/compare-slides.png`, `compare-sheet.png`, `compare-wall.png` and "
    "`compare-real-walls.png` (five of his own walls).\n"
)

replace_once(LOG, HEADING + "- **Stories kept here as they leave the runtime.**",
             HEADING + BODY + "- **Stories kept here as they leave the runtime.**")
print("log entry written")
