"""Success criteria (4.2.288): the build-log entry, written before the
independent checks so they can test it against the files. The stories bullet
(s1) stays last."""
from pathlib import Path

LOG = Path(r"C:\Users\Daniel\Projects\lessonv4\plugins\lesson-v4\references\build-review-log.md")
t = LOG.read_text(encoding="utf-8")
anchor = "*Topic 5 of the streamline in `plans/streamline-plan.md`: success criteria.*\n\n"
assert t.count(anchor) == 1
body = (
    "- **The inventory.** Every place the plugin says something about success criteria was listed: 392 places in 55 files (`plans/2026-09-23-success-criteria-ledger.md`). The core rules were written three to seven times each, fourteen places pulled against each other, seven examples agents copy from were in the shapes the rules forbid, and seven pieces of text no longer matched the plugin. An independent agent checked the list and found 36 places it had missed, most of them on the wall and the worksheet.\n"
    "- **The teacher's decisions**, sixteen, answered in one message and a read-back, are in the ledger in his words. Every taught word is green in the criteria, every time, and the designer still colours one or two other important words. Criteria are what a child who gets stuck looks at and uses to do the task, so in a lesson where children explain or write, sentence stems count. A condition that is part of a step stays in it; extra knowledge goes to sticky knowledge or the teaching. A method's steps are shown all together or not at all, and a slide that is only the criteria is for criteria being taught or built, never overflow. Criteria built live are offered to the wall, which decides, and go up as the exact same steps. There are no success criteria on any worksheet (\"I don't want any success criteria on worksheets\"). A second sentence in a step is not a fault in itself, but one that only names what the step produced goes, so his rounding rewrite lost `That's the ten below.` and `That's the ten above.` The wall never rewords a step and makes room instead. A criteria table stays a table. A wrap-around carries the first method's steps in their own words. A short question is a fine step (\"Same? Move right\" is \"short and snappy and it makes sense\"), which turns round the 13 September line that called it a slogan; his rewrite pair stays exactly. Only an action secure from earlier lessons is named without saying how.\n"
    "- **The homes.** `preferences.md` → Success Criteria holds what the criteria are, where they go and their colour; `teacher-voice.md` → 10. Success criteria how a step sounds, with his rewrites; the skill route's Writing the Success Criteria the step and table mechanics. The designer's own section became a pointer that keeps its self-check.\n"
    "- **Checked (code).** The validator refuses success criteria on any worksheet, and the launch check no longer offers taking a taught word out of the criteria. The worksheet engine refuses the criteria panel on a sheet (`CRITERIA_NOT_ON_SHEETS`); the panel stays in the engine for the colour marks the board and the wall share, and leaves the designer's catalogue. The panel's refusals on a slide name a roomier shape, never fewer criteria, and the capacity warning calls its numbers a cue to look. The review page's two cues on a step ask his questions (does a second sentence only name the result? does a question tell the child what to do next?) rather than pointing at a fault. The template guide no longer says the final slide check blocks on the criteria count, which it has not done since 19 September, and the test that held the old sentence now holds the true one.\n"
    "- **Pinned.** `success_criteria_ledger_pins.json` and `test_success_criteria_ledger_is_kept.py` pin every row, the three homes paragraph by paragraph, and the retired wordings as gone. Eleven rows of the earlier topics' pins whose words this change altered record the decision that changed them.\n"
    "- **Size, honestly.** The instruction files are about 3.2 KB larger (the worksheet designer and the designer's own section shrank; the home grew by the new decisions), the programs about 2.7 KB larger, and the worksheet catalogue about 0.6 KB smaller. Across the 53 saved designs, four now also carry the new worksheet refusal; nothing else changed.\n"
    "\n"
    "**Not done yet, and named.** Behaviour is untried on a real run. How to fit a very long criteria list on a slide (perhaps a new layout) is a separate investigation the teacher asked for, not started without his word. A method frame on a maths sheet (`method-frame`) names a method's steps on its working lines, and whether that counts as criteria on a sheet is his to say. The wall's layout test still uses `Find the neighbouring multiples.` as layout data, which no agent reads.\n"
    "\n"
)
t = t.replace(anchor, anchor + body)
LOG.write_text(t, encoding="utf-8")
print("log entry written")
