"""Release 7A (4.2.293), step 12b: the build-log entry, written above the story
`a1_stories_first.py` copied there first, in the style of the three
25 September entries: what changed and why, what is checked, what is pinned,
size honestly, and what is not done yet."""
from _patch import LOG, read, replace_once

HEADING = ("*Topic 7's 7A in `plans/2026-09-24-topic-7-change-plan.md`: starters, sticky knowledge, the Apply slide and "
           "the lesson's ends. The change scripts are in `plans/streamline-tools/7a-change/`.*\n"
           "\n")
STORY = "- **Stories kept here as they leave the runtime.** The content route once offered a second shape"
assert read(LOG).count(HEADING + STORY) == 1
assert "- **His answers.** On the starters, sticky knowledge and Apply list" not in read(LOG)

BODY = (
    "- **His answers.** On the starters, sticky knowledge and Apply list (24 September 2026): decisions 3, 7 and 9 "
    "\"Yes\"; the test-question starter \"get rid of the 'will return' stuff, it needs to be like it didnt even "
    "exist\"; practising a real test question \"keep with small fix\"; the starter's title and a teacher's own sticky "
    "facts \"yes\"; where a sticky fact sits, turned round: \"I dont think this needs to be a clear rule like 'sticky "
    "klnowledge statement always at top' ... That doesn't mean every slide I wanted was this structure\", with the "
    "because or so there to explain the one key point; the rest \"if you think they're fine, then yeah\". On the "
    "rest-of-preferences list: the Lesson 2 plan (decision 20), \"If so, I think that should come out because it "
    "already knows how much it can fit in one lesson\", then \"yes and yes\"; the change plan's question 2, \"yes\" "
    "(today still ends on its main idea while it is fresh; what the next lesson opens with comes out); maths titles "
    "(settled item 1) and `Practise` flagged (decision 21), \"yes\"; the wall keeps children's sentences whole "
    "(decision 22, its wording half), \"yes\".\n"
    "- **The test-question starter is gone as if it never existed.** The starter's always-empty `testQuestionPath` "
    "leaves the lesson file's contract, the validator (its key and its answer rule), the scaffold, the tests and the "
    "fixture, and the note that said the route \"will return\" goes with it. The tall-picture starter template stays, "
    "no longer described by a scanned question, and its two examples are now an ordinary starter from a saved deck (a "
    "Year 4 science starter, `Which teeth cut food?` and `Incisors cut food.`); its `question` slot keeps its name, "
    "which the code reads. The live rule for a real question from an upcoming test he supplies "
    "is unchanged, and its two short copies (the contents line and the reviewer's check) now carry both of its "
    "exceptions: the exact held item when he explicitly asks for it, and a real question that is not being held.\n"
    "- **The Lesson 2 plan is gone.** `lesson.scope`, `lesson.deferredLearning` and `lesson.lesson2Direction` leave "
    "the contract with their checks, the scaffold's request and output, the review view and the tests; a design or "
    "request carrying any of them is refused as an unknown field. The designer still fits one lesson properly and "
    "splits rather than crams, and a lesson that left something out says what in one line of the walk-through's "
    "closing decisions (whose \"related content deliberately deferred\" line is unchanged); it never plans the next "
    "lesson. How Much Fits keeps \"ending on the lesson's core idea while it is still fresh\" and loses \"make the "
    "production the opening of the next lesson\", the Roman diary example and a pointer to two research sections that "
    "carry no such mechanism; the designer's \"production opens next\" went the same way. The reviewer reads a split "
    "against the walk-through line, still asking that it be honest and visible, and the playbook's report says what "
    "was left in one line and no longer lists a lesson scope.\n"
    "- **The starter.** In history, geography and science a question the lesson will answer opens instead of recall "
    "only when the recall would be empty or the brief says the surface is already easy, and it stays a question "
    "children think and talk about, never a prediction or the task explained. The catalogue no longer invites a "
    "`title` under \"Starter\": only a `heading` the starter carries prints there, in his words \"Just the starter "
    "heading that's underlined is enough\" (the builder has done this since 4.2.256). The two mixed-retrieval "
    "formats in the activity list carry the Starters conditions in their own words.\n"
    "- **Sticky knowledge is written once.** `preferences.md` → Sticky Knowledge is the home: it takes \"trace each "
    "one forward\", the rule that a sticky fact is not where an idea goes (the pewter plates as its example), the rule "
    "that a fact giving away a later task's thinking is left off that task, and phrasing consistency, which now names "
    "the working wall. The designer's copy of the claim goes (it read as four alternatives where the home asks for "
    "all three), and its section keeps a pointer, the two examples beside the \"could a child have said it\" test, "
    "the recording and its three slide rules. A sticky fact the teacher's plan lists is judged like anything else in "
    "the plan and kept when he marks it required.\n"
    "- **Where a sticky fact sits: no fixed rule.** The landed sentence usually leads the board, usually as the "
    "headline, \"that is how this teacher usually explains, not a rule for every slide\"; a `takeaway` lands it last, "
    "as the star line, for a beat that withholds its fact and wherever the fact reads better last; whatever leads, "
    "the top line is never a caption of the picture. The content route, the skill route, the contract, the designer "
    "and the slide guide say the same; the validator already took either placement, so no program changed.\n"
    "- **The Apply.** `preferences.md` → The Apply Slide is the home of why an ending is earned and what it is "
    "judged against: it takes the designer's \"omit the ending when practice already draws on the intended "
    "learning\" and the three repairs in order, and names the intended learning as the read-back sentence that "
    "closes the walk-through and the sticky knowledge (the stale \"quality-lock sentence\" went). The ready-made "
    "reason for leaving it out stays for a lesson whose learning is a fact or a method; a lesson that named an idea "
    "says where the idea met a case it was not taught on (usually its Practise), or earns an Apply that takes it "
    "there, and the reviewer's routing card opens the Apply rules when it does not. The reviewer's test case that "
    "forbids demanding an extra Apply slide is unchanged. In maths, reasoning and problem solving are practise "
    "beats, and the last is the Apply only when it closes the lesson and asks more than the Your Turns did; a "
    "dialogic ending's kind is `Reflect`, as the program wants.\n"
    "- **Titles and numbering.** `Apply` is a slot name to replace outside maths only, in the four places that "
    "said so; the slide check flags a bare `Practise` in every subject and a bare `Apply` outside maths, with the "
    "maths note in its message; an untitled arithmetic grid no longer prints `Independent Tasks`: the slide check "
    "sends one back to be titled, naming the fix, and the final build draws it with no title line rather than lose "
    "the deck. A grid's calculations are its turn, so the title that fix asks for passes, and a grid under the "
    "starter header, which never prints a title, is not sent back for one. A title fault the designer's round leaves no longer costs the deck its drawings either: the slide "
    "decorator's check, and the orchestrator's after it, run with `--settled`, which prints a wording, title or "
    "layout fault as a note, while a fault the decorator's own drawings cause still fails; the slide designer's own "
    "check never runs with it (a test), since there every such fault must still send the deck back. The numbered helpers say "
    "the main independent work is numbered in maths only, and their labels are purple, as drawn.\n"
    "- **The wall keeps the lesson's sentences whole, and a card keeps its picture.** Asked (26 September 2026) "
    "whether the order for a card whose sentence does not fit should be the picture a little smaller first, then a "
    "bigger or second card, the picture off only when nothing else fits, and a sentence never cut, he answered: "
    "\"answer to your wall question, I guess, but I rarely also use cards with no picture or helper, so?\". Asked "
    "then whether a sticky fact too long to sit beside its photo should keep it, the photo shrinking further, to "
    "about a third of the card, so the whole sentence fits beside it, only then the sentence rewritten as a shorter "
    "whole sentence, and the photo off only as the very last move, he answered \"yys\" (yes). So the build's own "
    "first move is to let the picture give up a little width (the words' share of the card from 60% to at most 70%, "
    "about 72 characters an item beside a picture instead of 62), and a sticky fact that still does not fit keeps "
    "its photo, narrowed to about a third of the card, and runs to three lines at the smallest type (about 106 "
    "characters: every saved fact of 73 to 106 letters, 48 of them, now keeps its photo and its whole sentence). "
    "Asked last whether a long fact may run to three lines but a card holds only one of them, any other going on a "
    "second card, he answered \"yes\": so a card holds one fact on three lines, and the wall designer puts the next, "
    "in order, on a second card of the same type and title where the wall has room (the repair scope check now lets "
    "a focused repair's split leave a card one fact). A card that still holds more than one at build time is never "
    "lost for it, since his standing rule is repair first and a finished piece every time: the build takes his "
    "order's last move for that card alone, the photo off, every sentence kept whole, and says so, because a "
    "shorter sentence is the designer's to write and the build never writes words. "
    "Then a list goes over a second card; then the wall designer may shorten a sentence, only ever to a whole "
    "sentence, never cut to a clipped phrase (a sticky fact, like a definition, keeps the lesson's words unless it "
    "genuinely cannot fit); and the picture comes off last of all. A card whose words fit keeps its picture's full "
    "share. The wall designer's rule 8 is the home; its budget section and layout check, its Written Voice trigger, "
    "the wall preferences (two lines is what an item takes at the card's smallest type, which its budget measures, "
    "not a quota on writing, with the long sticky fact the one exception; its reason, the poster, kept; the taught "
    "term kept beside its plain words; 106 characters, not \"about 100\"), the focused repair and the build's "
    "refusal message follow in the same order, the message naming the budget at the widest share tried (72 "
    "characters beside a photo, not 62). A success-criteria step is never reworded, so its card makes room instead "
    "(the list over two cards, the picture off only when nothing else fits).\n"
    "- **The wall plans the page it draws.** The body fitter planned a card with a letter at 0.55 of the type size, "
    "a line 1.3 times it and 0.4in of panel edge; Chrome, which prints the wall, draws Comic Sans MS Bold by its own "
    "widths, wraps whole words, gives a line about 1.4 times the type and keeps 0.58in of edge, so a card could "
    "print past its panel (the Christmas wall's sticky card did, by 50 pixels). The five cards whose words wrap in "
    "a panel (sticky knowledge, a definition, a worked example, sentence stems and the misconception pair) now plan "
    "their bodies as drawn: each word measured with the board's width table (it matches Chrome to a hundredth of a "
    "pixel), the font's own line height, each item's padding, badge, bullet or label, the panel's real width and "
    "edge, and a stacked figure as drawn (its caption counted, and its real height rather than the reserve it is "
    "offered, which a wide figure often does not fill); the misconception pair as the two cells it draws, side by "
    "side under their labels, with the picture beneath taken from their height. The worked example's "
    "flat 0.2in badge reserve goes, since each row is measured at its badge's height, and a dominant figure, which "
    "sits beside the panel, no longer reserves room beneath it. Measured in Chrome, every saved wall and every card "
    "of the second check's sweeps keeps its text inside its panel. Nineteen of the 45 saved walls draw differently: "
    "on eleven a card's type is a size or two larger, where the old plan was too cautious; on five a card is a size "
    "smaller, where its words crowded into or past its panel's edge (four) or ran past the five lines one item may "
    "take (one); and on six a stacked figure is larger, the words' plan now needing less of the sheet. The character budgets still decide "
    "which card is refused. Arrows are drawn within the line: Comic Sans MS has none, and Chrome drew them from "
    "the stack's next font, Segoe Print, whose line is 1.78 times its type, so a line holding an arrow printed "
    "about 28% taller than planned (the rounding wall's steps 38px taller; 45 of 178 arrow cards in the third "
    "check's sweep past their panel). A \"Wall Arrows\" face now draws Segoe Print's own arrow, the one his walls "
    "had, 40% larger, so its shaft is as heavy as the digits beside it (11px at 60pt; Arial Bold's, tried first, "
    "was a 4px hairline), and holds it inside Comic Sans's line with the face's own ascent and descent, so a line "
    "holding an arrow is the height of one without and the plan needs no second font. A test builds an arrow into "
    "every place the face is written and measures the line and the shaft "
    "(`working-wall-html/test/every-arrow-is-drawn-from-the-wall-arrows.test.js`). "
    "Tested in Chrome, card type by card type: every item prints the lines it was planned, "
    "its height within a pixel and a half of the plan, and no text strays into a panel's padding "
    "(`working-wall-html/test/each-panel-card-prints-the-lines-it-planned.test.js`, and "
    "`nothing-prints-past-a-panel-edge.test.js` for the saved facts). The wall's other card types (titles, banners, "
    "headings, chips, grids, tables, posters, overviews) keep their own fitters, so no title size moves; a Chrome "
    "audit of all sixteen types on the fixtures and saved walls found text outside its box on one other card only, "
    "a diagram section's heading, 2.3 pixels past its strip. Its strip's padding now covers the words' overhang (a "
    "heading line is 1.15 times its type, the font's own box about 1.4) and its heading is measured as drawn. A "
    "standing Chrome guard (`working-wall-html/test/no-card-prints-outside-its-box.test.js`) builds every fixture, "
    "a diagram section and every saved wall in the checkout and fails if any card prints outside its box.\n"
    "- **Also corrected (settled item 12 and settled item 14).** The contents block (moved once: numbering, the "
    "Apply line, the test question, and the reviewer reading its always-read sections), the routing card's Pride "
    "Lessons note (it calibrates how much a beat carries and holds his chosen Teach slides; \"how often a lesson "
    "returns to the same evidence\" is another section's), and the `lesson-cover` template's \"historical reasons\".\n"
    "- **Pinned.** `scripts/tests/starters_sticky_apply_ledger_pins.json` with "
    "`test_starters_sticky_apply_ledger_is_kept.py`: all 390 rows where they now live, 65 changed rows each with the "
    "decision that changed it (five of them changed by the colours release first, mapped with its words), twelve "
    "added mechanisms, nine homes paragraph by paragraph (preferences' How Much Fits, Starters, Sticky Knowledge, "
    "The Apply Slide, Practising a Test Question and Purposeful Endings; the designer's Starter, Sticky Knowledge "
    "and Apply Slide), the 45 rows of the rest-of-preferences list 7A changed (release 7B takes them from the "
    "builder), and every retired wording barred in every instruction file and program, in any case where it is "
    "gone in any case. Thirty-eight pins in 28 rows of the earlier topics followed the words they held, each with "
    "the decision that moved them (rows: assumed knowledge one, quick checks five, success criteria eleven, the "
    "rhythm six, vocabulary three, worksheets one, colours one). The mapping is "
    "`plans/2026-09-26-starters-sticky-apply-mapping.md`.\n"
    "- **Checked.** Every suite passes (Python 2,280, voice 21, builder 772, worksheet 771, stick-in 73, wall 166, "
    "shared 126, test 46). The change scripts, replayed on a clean 4.2.292 copy, reproduce the working tree and "
    "the pins exactly. The 53 saved designs: stripped of the four retired keys, 52 give the same first fault as on "
    "4.2.292 and the other differs only by one fewer unfilled scaffold placeholder (the stripped key was one); as "
    "saved, 37 are now refused first on the three retired lesson keys and 16 on the same earlier check as before. "
    "A new lesson never carries the retired keys.\n"
    "- **Size, honestly.** The instruction files are about 3.3 KB larger: the lesson designer is 0.9 KB and the "
    "contract 0.6 KB smaller, but his decisions and the folds added words where they are read (preferences 1.8 KB, "
    "the wall preferences 1.7 KB, the activity list's two conditions 0.4 KB). The wall designer is 14 bytes larger "
    "and stays under its 51 KiB cap, which had 20 bytes to spare, by 6: its copies point at rule 8 rather than "
    "repeat it. The programs are about 27.6 KB larger: the retired fields came out of the validator, the "
    "scaffold and the review view (1.9 KB smaller), while the slide check gained the maths note, the untitled "
    "grid's message, a grid's turn and the settled check (3.1 KB), and the wall's fitter gained the page it draws, "
    "the picture giving way and the photo at a third, with its message in his order (22.2 KB, most of it the page "
    "model and why), the diagram section its heading strip (1.6 KB), the wall's fonts their arrows (1.6 KB), and "
    "the repair scope check the split that leaves a card one item (1.1 KB). The tests and pins are about 750 KB "
    "larger, 646 KB of it the new pin file.\n"
    "- **Not done yet.** Untried on a real run. A lesson designed before this release carries the retired keys, and "
    "its design is refused wherever it is checked again: a lesson already running when 4.2.293 is installed, or "
    "stopped and picked up again after it, is refused at the adaptation picture step (the run then drops its Below "
    "and Greater Depth sheets) and at any later review, and an old folder reopened to redo a resource meets the same "
    "refusals. So 4.2.293 is installed only between lessons, never while one is running. Rows of the later topics' "
    "ledgers that "
    "7A changed are listed in the mapping for their releases (routes, reviewer, playbook, voice). The two wall "
    "glance tests and the wall's example sticky card are topic 9's. The wall's plan measures Comic Sans MS as the "
    "classroom machine prints it; a machine without the font prints a wider fallback, as it always has.\n"
)

replace_once(LOG, HEADING + STORY, HEADING + BODY + STORY)
print("log entry written")
