"""The design reviewer release, step 8: the build-log entry, written above the
stories `rv_01_stories_first.py` copied there first. No version number: the lead
numbers the release at merge (and bumps both plugin.json files then)."""
from _patch import LOG, read, replace_once

HEAD = ("## 2026-09-26 - The design reviewer mends the words itself and names the bigger fixes for the lesson designer, "
        "judges the board before the notes, and opens the three sections its checks send it to\n"
        "\n"
        "*Topic 8 of the streamline in `plans/streamline-plan.md`, its release 2: the design reviewer. Built on a side "
        "branch; the version is set at merge.*\n"
        "\n")
assert read(LOG).count(HEAD) == 1
assert "- **Why.** Topic 8's first list, the design reviewer" not in read(LOG)

BODY = (
    "- **Why.** Topic 8's first list, the design reviewer (`plans/2026-09-23-design-reviewer-ledger.md`): 428 places in "
    "26 files that say something about the independent review of a finished lesson design. He answered every decision "
    "on 24 September, in his words in that ledger. This is `plans/2026-09-24-topic-8-change-plan.md`'s release 2 "
    "(section 3).\n"
    "- **The reviewer mends the words; the lesson designer makes the bigger fixes, and the reviewer names them "
    "(decision 2).** \"if it's a small thing, say it's words aren't right and it thinks these words would be better, "
    "then the reviewer changes them ... Swapping a photo of a number line for a drawn one or rewriting a doobie. Sounds "
    "like it should be for the lesson designer\", then \"1. y\". Two checks had worded those fixes as the reviewer's "
    "own, against the same file's rule that a fix changing what children see or have to think is the lesson designer's. "
    "A Do that says its Teach back now goes back to the Lesson Designer with the fix named (\"The repair keeps the chunk "
    "and is the Lesson Designer's, because it changes what children have to think\", the list of repairs unchanged), and "
    "so does a photograph of a tool the engine draws, naming the helper that should draw it. A Teach example written as "
    "an instruction to look stays the reviewer's own wording fix, word for word as it was: the release first sent it to "
    "the designer, the first independent check found his words keep a wording fix with the reviewer, and asked with "
    "\"Look at the diagram.\" whether the reviewer rewrites it itself as what children will notice (\"Notice the enamel "
    "is the hardest layer.\"), he said \"yes\" (26 September). The reviewer's other wording repairs stay its own too: a "
    "clause that says who a name is, a question carried from the script onto the board, a second accepted placement in "
    "an answer key, the voice sweep. The reviewer's behaviour list gains the two send-backs, each with the fix named, "
    "and his example as the reviewer's own correction. What a send-back costs: "
    "everything one review sends back goes to the lesson designer together, in one pass with the whole diagnosis, and "
    "a run allows two such passes. If the review after the second still finds one, the playbook tells the run to "
    "build the lesson from the last design, which still passes every check, to carry the unresolved finding into the "
    "run report's blocking faults and his teacher flags, to lead his report with it, and never to end the run "
    "complete; the fix it named is not made. That last part is held by the playbook's words, not by a program: the "
    "run report check passes a report marked complete while the last review still says `REDESIGN REQUIRED`, if the "
    "finding was not carried over. The missing check is carried to the playbook's run-faults release.\n"
    "- **The routing card opens the three sections the checks send the reviewer to (decision 7, \"2. yes\").** The card "
    "is the reviewer's whole reading assignment, and three checks pointed at `preferences.md` sections for cases the "
    "card never listed, so none was opened for them. Each trigger gains one sentence that fires on something the "
    "reviewer can see before judging anything, and names the paragraph it is for: Slide Philosophy's `Lesson Designer "
    "content boundaries` whenever `Names on the board` lists a real person, place, organisation or event, for `A name, "
    "or a thing the class has never met, arrives with its context` (a made-up person or a label such as `Chart A` is "
    "not this case); the visual-need boundary whenever a beat quotes, voices or names a made-up person who is present "
    "in it (one only referred back to is not this case); Source and Scenario Integrity when a made-up person or story "
    "stands for a group the objective is about. The name case opens only the subsection that holds its paragraph, about "
    "18 KB, rather than all of Slide Philosophy's designer parts, about 34 KB. Its first wording, any listed name, fired "
    "on 41 of the 53 saved designs, many for made-up children in maths and PSHE questions, labels such as `Chart A` or "
    "`Day A`, and words the list takes for names (`LESSON`, `PSHE`); the release's first independent check found it, "
    "and in the paragraph's own words it fires on 19 of the 53 (`plans/streamline-tools/rv-name-trigger.md`, design by "
    "design). The second check found the list itself missed a one-word name that opens its board sentence "
    "(`England, 1485 to 1603.`, `Bruegel painted ...`), capitalised there only for being first; a word the teacher's "
    "script capitalises mid-sentence now counts as a known name, as a word the board capitalises mid-sentence already "
    "did, and a name only the script says is still never listed. Every saved design's card differs from before in "
    "exactly those three lines; seven review views list one or two more names (`England`, `Bruegel` and made-up "
    "children), and no other line of any view changes.\n"
    "- **The board first, the notes separately (settled item 4).** \"maybe it should look at the board first. Judge the "
    "board first ... So maybe it should be board first, speaker notes separate.\" The route check's \"Judge the spoken "
    "and visible explanation together\" is now \"Judge the visible explanation first, on its own, and the spoken one "
    "separately, so nothing counts as taught on the board because the script says it\"; its second half is unchanged. "
    "The Teach-board check's \"Then uncover the script and read the two together\" stays: it is the comparison that "
    "finds a sentence only the script teaches.\n"
    "- **Out-of-date lines say what is true (settled item 5).** The report shape shows the `Closest to a repair:` line "
    "and its three quoted strings under the count line, which the after-review check already refused a report "
    "without; a validator failure after the review goes to the reviewer's own focused repair first and only then to a "
    "fresh design attempt; \"The design now states this in each unit's `unlocks`\" loses \"now\". The playbook's two "
    "lines about the retired final review are the playbook release's, and the preferences contents line is 7A's, as the "
    "plan agreed.\n"
    "- **One copy of each rule (settled item 10).** Out: \"Do not recheck identifier or reference legality.\" (the "
    "validator list says it), the line before the drift check that repeats the reading order (the reading list says "
    "it), the section 4 bullet that pointed at the amount test (the User-fit judgement owns it) and \"do not repeat a "
    "separate whole-lesson sweep\" (the review method's opening says it). \"Use `REDESIGN REQUIRED` when ...\" moves "
    "word for word beside `APPROVED`'s line. The near-repeats keep their own words: \"one clear\" bounded change, the "
    "noted wording judged in its context, the objectives checked again after corrections, the placeholders explained.\n"
    "- **The stories leave; the reasons stay (settled item 11).** Nine dated incidents in the reviewer's instructions "
    "went, each copied here first, below: the history design of 10 September, the Tudor deck of 14 September, the two "
    "lessons of 22 September, the class that met a planning noun after a review found nothing, the count-only sweep on "
    "the PSHE lesson, the RE beat's compact question, the RE deck's text cards, the place-value chart sheet, and every "
    "sheet counted on 12 September (the last two the worksheets plan left to this release). The two script lines from "
    "22 September, `What do their reasons share?` and the teeth sheet stay as plain examples, and \"today the teacher "
    "edits it out by hand\" now says the teacher would have to.\n"
    "- **The child the sweep imagines is the child in this class.** \"the actual eight- or nine-year-old the year group "
    "names\" became \"the actual child in this class\". This is the lead's reading of his words, not his wording: on the "
    "rest-of-preferences list (24 September) he said \"I actually don't know why it says nine-year-old. Um, because the "
    "plugin is for years one, two, three, four, five, and six, right?\" of other lines, and the lead carried it to this "
    "one, in these words.\n"
    "- **Left exactly as it was.** His \"about four pieces\" calibration (\"not if it hassnt been broken anyway\"), the "
    "effort settings, every heading and marker the after-review check reads, and the two paragraph openings the voice "
    "harness reads.\n"
    "- **Pinned.** `scripts/tests/design_reviewer_ledger_pins.json` holds all 428 rows: 393 where they stand; 34 "
    "changed, moved or retired, each with the decision that changed it and its whole paragraph (nine of them changed by "
    "the success-criteria, worksheets and subject-files releases after the list was made, mapped to their words); and "
    "C10, the Teach example written as an instruction to look, kept as it was and mapped with his answer, the words that "
    "first sent it to the designer barred; the behaviour cases decision 2 and his answer added; and the reviewer's instructions section by section, paragraph by paragraph. "
    "`test_design_reviewer_ledger_is_kept.py` runs the shared checks and a test per decision. Earlier topics' pins "
    "followed the words in place, each with its decision, and each topic's ledger says so: AK-A49, G21, K01; QC-C08, "
    "D08, E11, P01; SC-Q01; TD-L07, L09, L10; WS-I05, Q02, Q08, Q10, Q11 and the worksheets section's home.\n"
    "- **Checked.** Every suite passes: Python 2,276 passed and 1 skipped (4.2.292: 2,255 and 1; the new pin test and the card, fixture, name-list and report-shape tests add twenty-one), the voice harness 21, and the builder 762, the sheet engine 771, the stick-in pack 73, the wall 154, shared 126 and the root tests 46, each as on 4.2.292 because no engine changed. The 53 saved designs give the same result as on 4.2.292, design by design. Every saved design's routing card differs from before in exactly the three trigger lines; seven review views list one or two more names, and nothing else in any view changes. Each of 38 changes, undone one at a time on a copy, is caught by a test. Replayed on a clean 4.2.292 tree, the scripts make this tree exactly. A trial merge with 7A's commit conflicts only in this log and three pin files, as expected, and once they are resolved and `plans/streamline-tools/rv-change/rv_09_follow_at_merge.py` has run the whole Python suite passes on the merged tree (2,301 and 1 skipped).\n"
    "- **Size, honestly.** The reviewer's instructions, read whole every review, are 1.3 KB smaller (74,602 to 73,271 bytes): the stories and repeats took out 2.0 KB, and his decisions put 0.7 KB back where they are read. The review packet program is 2.1 KB larger (the three triggers, and the name list reading the script). What the card now opens is where the reading grows: Slide Philosophy's content boundaries, about 18 KB, in a lesson whose board names a real person, place, organisation or event (19 of the 53 saved designs), when nothing had sent the reviewer there already; the picture rules, about 15 KB, for a made-up person in a beat; Source and Scenario Integrity, about 6 KB, for a made-up case standing for a group. The tests and pins are about 580 KB larger, 551 KB of it the new pin file, and this log gains this entry and its stories, about 15 KB.\n"
    "- **Not done yet.** Untried on a real run. Release 7A is merged first and changes seven rows of this list (its "
    "split and test-question lines, the maths `Apply` title, the Pride and Apply card notes, the preferences contents "
    "line); the mapping follows them when it is rebuilt on the merged tree. 7B's pointer on the User-fit paragraph and "
    "its launch pointer are still to come and will meet this release's words there. Sixteen rows of the rest-of-"
    "preferences list and two of the voice list quote lines this release changed; the mapping names them.\n"
)
replace_once(LOG, HEAD, HEAD + BODY)
print("log entry written")
