"""The voice guide release, step 8: the build-log entry, written above the stories
`vg_01_stories_first.py` copied there first. No version number: the lead numbers
the release at merge (and bumps both plugin.json files then). Two of its
sentences are pinned by the mapping (`VG-DEC-LOG`), so this runs before
`build_vg_mapping.py`."""
from _patch import LOG, read, replace_once

HEAD = ("## 2026-09-26 - The voice guide sends every kind of writing to its own part, humour is welcome in every "
        "subject, a class the lesson comes back to gets a lively name, and speaker notes are as long as the idea "
        "needs\n"
        "\n"
        "*Topic 8 of the streamline in `plans/streamline-plan.md`, its release 5: the voice guide. Built on a side "
        "branch; the version is set at merge.*\n"
        "\n")
assert read(LOG).count(HEAD) == 1
assert "- **Why.** Topic 8's fourth list, the teacher voice guide" not in read(LOG)

BODY = (
    "- **Why.** Topic 8's fourth list, the teacher voice guide (`plans/2026-09-23-teacher-voice-ledger.md`): 470 "
    "places in 58 files that say how the words children read and the teacher says should sound. He answered every "
    "decision on 24 September, in his words in that ledger. This is `plans/2026-09-24-topic-8-change-plan.md`'s "
    "release 5 (section 6).\n"
    "- **Every kind of writing is sent to its own part (decision 1, \"yes\").** Nothing sent a writer to the guide's "
    "§7 (sentence stems and other support) or §14 (tone by kind of lesson). A sentence stem or other support now opens "
    "§7 when it is written, and §14 is read once, when the kind of lesson is settled.\n"
    "- **Four kinds are the most often missed, and one route sends the writer to each (settled item 1).** The guide "
    "named questions and comparison prompts as the two most often missed, the lesson designer definitions and "
    "scripts; each came from a real miss, so the guide's route names all four, each with its reason, the designer's "
    "reason moving there nearly word for word, and the designer reads the guide by that route instead of keeping a "
    "shorter copy of it. Its pointer to `Say what you mean` with assumed knowledge's reason, its line on reading §4 "
    "once, and its line sending the first script to the two full scripts in §16H all stay. Its copy sent \"a "
    "comparison or critique prompt\" to §12, where the guide's route said only a comparison prompt; the route now "
    "says both, so the fold keeps the critique.\n"
    "- **Before the case means before the question about it (decision 2, \"yes\").** The slide rules' case-context "
    "paragraph gains one sentence: when the thing is on the board, the sentence about the thing in view comes first "
    "and the general one straight after. His own order in the guide (`This tooth has lost a piece of enamel.` before "
    "`Sometimes, teeth can be chipped or broken if they take a hard knock.`) does not change.\n"
    "- **The slide designer opens the speech guidance for anyone who speaks (decision 4, \"yes\").** After the "
    "carol-singing deck the guidance widened its own opening to anyone who simply says what they think, gives their "
    "reason or asks a question, but the three lines that decide whether the slide designer opens it still listed only "
    "a speaking character, a claim, a misconception, a disagreement or advice to a character. All three now carry the "
    "guidance's own list, word for word, and the first keeps the opening a test holds.\n"
    "- **Humour wherever (decisions 9 and 10, turned round).** \"Humour wherever, but I still never see it on "
    "slides!\" and \"humour is allowed in pshe\": the guide's `When humour is optional` now says every subject, maths "
    "and PSHE included, in his words. His \"i also wasnt humour in pshe slides too, never maths\" of 12 September "
    "(4.2.151) stays in this log as history, and \"never maths\" no longer stands; no instruction had carried it. "
    "Calculation steps still often work best without humour, the sensitive-issue limits and \"none is the right "
    "answer\" stay, and the melons line stays as an example, as his read-back said. Why a light line never reaches "
    "the board is release 6's, after his answer on the diagnosis (`plans/streamline-tools/humour-diagnosis.md`); this "
    "release carries only the parts the diagnosis names for it: his words recorded, and the two copies that said a "
    "conversational line never goes on the board brought to \"normally\".\n"
    "- **A class the lesson comes back to gets a lively name (decision 11).** \"Named but not always class 4a 4b etc, "
    "jazz it up.\" The lesson designer's invented group gets a name the first time, and not always a class code like "
    "`Class 4B` (`Oak Class`, `the class at Hilltop School`, `the Hill Road team`), used every time the lesson speaks "
    "about it; \"plain ordinary\" went with his \"jazz it up\". The guide's §6 gains the same clause beside its "
    "examples, which stay.\n"
    "- **The discussion is not scripted; the words that open it are (decision 12, \"yes\").** The dialogic route's "
    "\"Do not turn the notes into a compulsory script\" now says so, which the program's script on a combined "
    "stimulus-and-talk unit already agreed with.\n"
    "- **The slide is normally the tighter version (settled item 5).** The guide's \"Do not normally reverse\" is his "
    "calibration finding, and his own calibrated slides put a conversational line on the board (`Now break it.` with "
    "`Not literally!`; `The clue is in the name!`), which \"never\" would forbid. The lesson designer's \"never the "
    "reverse\" and Written Voice's \"not the other way round\" now say \"normally\" too.\n"
    "- **Keep precise subject vocabulary (settled item 6).** Honestly, of its 32 copies almost every one carries its "
    "own condition for its own reader and stays, the script's two among them. The two plain repeats folded: the "
    "adaptation reference's line, two lines above its fuller copy, is cut, and the adaptation designer's copy points "
    "at Written Voice's Below paragraph, keeping both halves (kept, and supported rather than replaced).\n"
    "- **Out-of-date lines say what is true (settled item 8).** The guide's full-script note put a caveat or a "
    "safeguarding note in \"the teacher line above\", which prints below the script; it now names both lines (a "
    "caveat below, in the teacher information; a staging line for a model finished live above, in `On the board:`). "
    "The em dash leaves the list headed \"Avoid these unless the context clearly justifies them\" for a line of its "
    "own that says never, as Written Voice and the program already do. The notes hand-off names where the two "
    "full-length scripts are (§16H). The lesson designer's \"That section is the one place every vocabulary decision "
    "is written\" read as the voice guide's §5, which holds none of them; it names `preferences.md` → Vocabulary. The "
    "guide's Maintenance note sat inside §17, which the reviewer is shown every review; its maintainer lines moved to "
    "the voice harness's read-me, and \"Treat this guide as the default runtime specification.\" stays in the guide. "
    "The harness's read-me no longer calls the held-out file empty, and its sweep runner no longer calls the "
    "reviewer's register paragraph \"the paragraph before\" the sweep. Long dashes in examples a child could be given "
    "are replaced in the activity list (four), the dialogic and task routes, the research file and preferences (three, "
    "which 7B has not reached); those in `templates.md`, the wall files and the messages to him are topic 9's.\n"
    "- **Speaker notes are as long as the idea needs.** His answer on the rest-of-preferences list: \"speaker notes "
    "are as long as the idea needs, of course, and they're also conversational, so it links them nicely. It's talking "
    "to children. It just needs to think how can I talk to children to get them to understand it\", pointing to his "
    "week 3 science lesson (how a tooth decays, taught 23 September) as wording to study. The guide's §2, which every "
    "script's writer reads, gains his words and five short lines from that lesson's notes, quoted exactly: the length "
    "is the idea's, each note picks up where the last left off, it talks to the children about themselves, it asks "
    "and answers so the class thinks along, and a phrase repeated for rhythm is how speech builds. The deck itself is "
    "not copied into the plugin. Shown the points and asked about the last, he said \"yes thats fine\" (26 "
    "September): a phrase said again for rhythm (\"a tiny bit ... a tiny bit more\") belongs in a script, and the "
    "guide's warning against sentences of one repeated shape (§3) now says it stands on the written board and page, "
    "the repeated phrase in speech its one exception.\n"
    "- **Decision 13 (a nine-year-old in four places) and his answer in the lesson designer's own notes line are built "
    "here, brought from release 7B by the lead** after this release's first check, so the designer that writes every "
    "script and the guide no longer pull against each other; in 7B's planned words and his (\"for the speaker notes "
    "it doesn't have to be short sentences\"; \"the plugin is for years one, two, three, four, five, and six\"). The "
    "designer's notes voice, which said \"clear simple language a nine-year-old follows easily, short straightforward "
    "sentences\", now reads \"as long as the idea needs and conversational, in words the children in this class follow "
    "(the teacher: \"it doesn't have to be short sentences\")\", and asks how you would say it so these children "
    "understand it. The notes hand-off gains his words beside \"chosen for the idea rather than a mechanical "
    "simplicity rule\". Each other line that fixed a nine-year-old reader now says a child in this class: a sort's two "
    "groups, the own-question test in preferences, and the adaptation designer's Greater Depth line, whose example "
    "now names its child (`Is Asha right about all of it?`, his settled correction on the rest-of-preferences list, "
    "fixed in the same edit as 7B's plan had it). 7B no longer carries these; the hand-off naming the notes' lines in "
    "the order they print stays 7B's.\n"
    "- **Left exactly as it was.** His calibration examples, among them the two another list called stale (the "
    "success-criteria example's objective without \"To\", and the stem example's `will not` for the question's "
    "`won't`), which his standing rule and the voice list's settled item 7 keep exactly (the plan's risk 15); both "
    "orders of his \"quick, punchy and summarised\" words, each place keeping its own; the melons line; settled items "
    "3, 7, 14 and 15.\n"
    "- **One budget widened.** The slide designer's focused repair carries the speech guidance's list, word for word, "
    "like the other two triggers, and that took its compact entry point to 8,034 bytes, over the 8,000 every focused "
    "repair is held under. Its budget alone is now 8,200, and every other repair role keeps 8,000. The lead chose "
    "this over giving that one trigger a shorter wording: his words kept whole beat a byte guard, and the file stays "
    "about an eighth of the full slide designer it stands in for.\n"
    "- **Pinned.** `scripts/tests/teacher_voice_ledger_pins.json` holds all 470 rows of the list: 430 where they stand; "
    "33 changed, moved or retired by this release, each with the decision that changed it and its whole paragraph; 7 "
    "changed by earlier releases after the list was made (colours, 7A, the design reviewer, and the subject files' "
    "three removed with their files), mapped to their words; seven added rows (the case clause, his speaker-notes "
    "lines, the phrase repeated for rhythm with his answer, the replaced dashes, the harness's new section, decision 13's line that has no row, two sentences of "
    "this entry); and the voice guide's sections, all but §10 (the success-criteria topic's home), paragraph by "
    "paragraph. `test_teacher_voice_ledger_is_kept.py` runs the shared checks, reading the voice harness and the "
    "builders' shared text code too, and a test per decision. Earlier topics' pins followed the words in place, each "
    "with its decision, and each topic's ledger says so: AK-B04, B19, B20, B27, F01, G09, G19; QC-A18, B06, G06 and "
    "the rhythm home; SA-B18, J43, L21, PF-I06, PF-V16 and the starters home; SC-D42; TD-C19, G09, J62 and the rhythm "
    "home; VOC-A02, C24, P02, P03, DEC-10 and the designer's vocabulary home; WS-F20. The mapping is "
    "`plans/2026-09-26-teacher-voice-mapping.md`.\n"
    "- **Checked.** Every suite passes: Python 2,325 passed and 1 skipped (4.2.294: 2,301 and 1; the new pin test "
    "adds 24), the voice harness 21, and the builder 772, the sheet engine 771, the stick-in pack 73, the wall 166, "
    "shared 126 and the root tests 46, each as on 4.2.294 because no engine changed. The 54 saved designs give the "
    "same result as on 4.2.294, design by design (no program changed). Each of 60 changes, undone one at a time on a "
    "copy, is caught by a test. Replayed on a clean 4.2.294 tree, the scripts make this tree exactly. A trial merge "
    "onto main with the routes release committed (4.2.295) merges every instruction file cleanly; six ledgers, this "
    "log and the rhythm's pin file conflict because both releases append to them, and once main's side is taken and "
    "`plans/streamline-tools/vg-change/vg_09_follow_at_merge.py` has run, the whole Python suite passes on the merged "
    "tree (2,382 and 1 skipped) and the voice harness 21.\n"
    "- **Size, honestly.** The instruction files are 2.5 KB larger, not smaller. The voice guide is 2.1 KB larger "
    "(58,586 to 60,642 bytes), where the plan expected 1 to 2 KB smaller: the stories and the Maintenance note took "
    "out about 1 KB, and his speaker-notes answer with its five lines and the rhythm exception, his humour words, the class "
    "clause, the two routed sections and the full staging note put about 3 KB back; §2, which every script's writer reads, is "
    "where most of it is, and §17, which the reviewer is shown every review, is 0.6 KB smaller. The lesson designer "
    "is 0.2 KB smaller; the slide designer's three triggers are 0.3 KB larger; preferences 0.4 KB larger; the "
    "adaptation files 0.1 KB smaller. The voice harness's read-me, which no lesson reads, is 0.7 KB larger. The tests "
    "and pins are about 660 KB larger, 625 KB of it the new pin file, and this log gains this entry and its stories, "
    "about 17 KB.\n"
    "- **Not done yet.** Untried on a real run. Humour on the board is release 6's, after his answer on the diagnosis. "
    "The lesson designer's four register tells and the reviewer's voice sweep still name adjacent sentences of one "
    "shape as a slip in any string; a phrase repeated inside a spoken sentence is not that, and neither was changed. "
    "The routes release merges first: its merge conflicts with "
    "this one only in the pin files and ledgers both append to and in this log, and the follow-at-merge script puts "
    "this release's words back and maps the three rows of this list that release rewords. The voice harness measured "
    "nothing here: it waits for his labels, and this release's speaker-notes lines are the kind of voice change it "
    "exists to measure.\n"
)

replace_once(LOG, HEAD, HEAD + BODY)
print("LOG_ENTRY_OK")
