"""Assumed knowledge (4.2.287): the build-log entry, written before the
independent checks so they can test it against the files. The story bullet
already there (a5) stays last."""
from pathlib import Path

LOG = Path(r"C:\Users\Daniel\Projects\lessonv4\plugins\lesson-v4\references\build-review-log.md")
t = LOG.read_text(encoding="utf-8")
anchor = "*Topic 2 of the streamline in `plans/streamline-plan.md`: what children are assumed to already know.*\n\n"
assert t.count(anchor) == 1
body = (
    "- **The inventory.** Every place the plugin says what a lesson may take children to know already was listed: 283 places in 38 files (`plans/2026-09-22-assumed-knowledge-ledger.md`). \"Work from what children can use at that point\" was written in full once and in shorter forms seven more times, several of them carrying a condition the full rule lacked; the source test and the beat-by-beat knowledge check lived only in the history file although the designer's general rules sent every subject to them; the review page's list of names missed a one-word name at the start of a sentence, never read slide titles or vocabulary cards, and counted the teacher's script and part-words as \"said earlier\". An independent agent checked the list before it went to the teacher.\n"
    "- **The teacher's decisions**, eleven, answered in one message and a second round on the read-back, are in the ledger in his words. The board and the notes are never one thing: the board holds the teaching, the activities, the helpers and the pictures to point to, the notes are the script for saying that slide to a cover, tired or new teacher, most of the time a teacher does not read them, and nothing is taught by the two together; the designer's final check no longer counts \"spoken preparation\", the reviewer's panel line gives a spoken reason C04's two directions, and history's judged-person sentence is \"on the board\". A plan's earlier lessons are rough context, taken as taught, and anything today leans on from one of them gets a short reminder where it first appears (`Lord Shaftesbury, who we met last week, ...`), never a reteach; Connect It Back's older idea is \"familiar once it has been brought back\". A name, or a thing the class has never met, arrives with its context in the sentence that brings it in, in every subject, and the repair is in the wording, not a vocabulary card (his words: set the scene, `Elizabeth I was the Queen of England at that time. She was worried about ..., so she wrote something called an order. This is it.`). Where a source came from is said once, in the class's words, only when it matters, and `reconstruction`, `modern summary` and an organisation's name stay off the board unless taught.\n"
    "- **The homes.** `preferences.md` → What a Lesson Is For holds `Work from what children can use at that point` with every extra its copies carried (a freshness repair, each case seen worked, a new reasoning demand and maths's fuller form, an invented wage, trick wording and avoidable reading, what the task and its answer may claim, the same conclusion earned case by case, a Practise brought forward) and the beat-by-beat check for every subject, with the moves that ask first on purpose (a hook, a pattern, an exploration, a first attempt, an estimate, fresh evidence). Source and Scenario Integrity holds the source test (\"new to the topic\") and the one rule on children's own experience (invited, never required, the alternatives in the words the class hears). `teacher-voice.md` §6 holds the four shapes of a question written by someone who knows the answer beside its two repairs; the slide rules keep a pointer naming them. History keeps its opening, the 1590 order, the Egyptian example and its enquiry, and points home.\n"
    "- **Checked (code).** The review page's `Names on the board` now reads slide titles and vocabulary cards, finds a one-word name at the start of a sentence when the lesson capitalises the same word elsewhere, ignores a title written with every word capitalised (`Look Closely`) and the opening verbs a title starts with, and says \"said earlier on the board\" only when the board showed the whole word. Across every saved design it found twenty more real names (`Tudor` at a sentence start, `Parliament` on a card, children's names in titles) and lost none; `Source` and `Factory` on their own are the noise it adds. The reviewer reads `preferences.md` → Vocabulary on every review, for the rule on an ordinary word a sentence leans on (`government`, `order`), which no list can see.\n"
    "- **Pinned.** `assumed_knowledge_ledger_pins.json` and `test_assumed_knowledge_ledger_is_kept.py` pin every row, the three homes paragraph by paragraph, and the retired wordings as gone. Eight rows of the earlier topics' pins whose words this change altered (and two whose whole-paragraph pin on the contents list moved) record the decision that changed them. Five rows of this ledger were changed by the Teach then Do topic after its snapshot, and say so.\n"
    "- **Size, honestly.** The instruction files are about 7.4 KB larger and the review page's code about 4.4 KB. Most of it is new wording the decisions asked for (the name paragraph, the general knowledge check, the extras in the one home); the two folds moved text rather than shortening it. The reviewer also reads the 15 KB vocabulary section on every review now.\n"
    "\n"
)
t = t.replace(anchor, anchor + body)
LOG.write_text(t, encoding="utf-8")
print("log entry written")
