"""The routes release, step 9: the build log entry, written above the stories
`rt_01_stories_first.py` copied first. The heading carries no version number:
the lead numbers the release at merge."""
from _patch import LOG, read, write

HEADING = ("## 2026-09-26 - The teacher's way of explaining is written once for every kind of lesson, a class sees "
           "a good explanation before it writes one in every route, four corners is gone, and the routes' "
           "out-of-date lines are put right")
STORIES = "- **Stories kept here as they leave the runtime.** The route files, the activity list and the modelling file"

BODY = """*Topic 8's release 3 in `plans/2026-09-24-topic-8-change-plan.md`: the teaching routes and the pedagogy references, his decisions and the corrections. The change scripts are in `plans/streamline-tools/rt-change/`.*

- **His answers.** On the routes list (24 September 2026): "1. y. 2. y 3. thats how i explain anything, so might not neccearily be teach slides i guess 4. y 5. y", and "y" to the settled items. His starters answer the same afternoon gave the parts of his way of explaining: the because or so "just to explain that one key point", "then addressing a misconception or pointing to an example". Asked then whether a maths My Turn should count as the good explanation children see before writing one, he said "Yes" to: a My Turn or Our Turn counts only when it shows the kind of thing children then write. His preferences decision 13b (success criteria that already show what a good one looks like need no second model) was moved here from 7B so the words land with the code.
- **Moving about.** Four corners comes out of the discussion route: a Stimulus can be a ranking, a sort or a vote with a written reason, and a Talk's formats offer a line on paper from agree to disagree or a vote with a written reason (the activity list's 6.2 and 6.4). Role-play, hot-seating and a short debate still come only after every child has written or chosen a side. The activity list lets a whole-class movement beat go ahead without his asking only when the movement is itself what is being learned (standing and making a quarter turn to learn what a quarter turn is), which the designer's enactment sentence and the skill route's recognition paragraph already said.
- **A class sees a good explanation before it writes one, in every route.** The design check that refused a knowledge lesson's written explanation or comparison when nothing earlier had shown a good one now covers a skill lesson's Practise and a task lesson's Do the task too. A My Turn or Our Turn no longer counts just by being a turn: it counts when its own question asks for an explanation and its good one is on the board (its model answer revealed, or a My Turn's exemplar written live). A task is an explanation by the explanation-task fields (`reasoningWords`, `rehearsal`) or, on a Practise, its stated form; a Do the task's description is not searched, because an enquiry that compares two materials is not a written comparison. The task route's line that let a launch go when "the product form is familiar" takes the knowledge route's rule, both output blocks gain its second case (a good one shown earlier in this lesson), and the task route's own trigger for a launch asks whether the class has seen a good one in this lesson rather than whether it has made one (his decision names that line, though the plan had kept it). 13b is in the launch home and its three pointers in the same words, and in the two output-block lines it came from: success criteria that already show an actual good one (his example: "a writing task whose criteria already show a good paragraph"), never a list of what a good one includes, stand in for the good instance, so the launch keeps its case and steps and needs no second model. No criteria shape holds a written model, so the program cannot see one, and it keeps asking a written explanation for its good instance; the reviewer judges the claim for anything else. (The first build passed any launch whose beat carried criteria; the first check found three saved maths lessons that would then have passed with a one-line launch and no explanation, because their rounding steps were attached as criteria, and a history comparison passing on a checklist of what a good comparison has. Both are refused now.) The reviewer's launch line takes decision 2's words too: a launch when the class has not yet seen a good one of this product earlier in this lesson, rather than "when the product's form is new to the lesson", and a null launch also when it has.
- **His way of explaining, written once.** The content route's output block ends with two headings, `How this teacher explains` and `The launch`, each holding the paragraphs that were there, moved word for word, so the bundled reader can hand either to another route whole. The bold sentence that called his four parts "the shape this teacher teaches in, more often than not" is his read-back: how he usually explains anything, on a Teach board in any kind of lesson or wherever else something is explained, the takeaway, then a because or so that explains that one key point, then an example or what it does not mean, not a template. One paragraph names the field that carries it in each route and the two exceptions and where they live: a skills lesson's teaching board stays brief, and a discovery lesson lands its takeaway at the end, because children reach it themselves. The skill, task and discovery routes replace their older three-line shape with a pointer there, each keeping its own length and exception; the skill route's output block now says which fields its `teach` and `practise` beats take and where their rules are; a dialogic grounding input that explains points there too. The section says only what is true when another route reads it alone: the validator refuses a null `explanation` on a `teach` beat, not on a task lesson's `teach-needed`, and its two back-references name the fault inside it. The designer reads the two sections with the bundled reader when its route is not the content route; its walk-through line, the reviewer's four-parts line and the preferences' pointer name the heading, and the voice guide's §5 says an explanation usually goes that way and is not a template.
- **Planning, the Look for note and a big task's teaching.** Planning and doing are one flowing task, a check for safety or wasted materials inside it as the teacher's check, and the plan gets its own beat only when it produces something children need before they start. The explanation-task guidance puts the one link most children skip, and its question, in the 25-word Look for note, and the other likely gaps in the teacher's note beside the likely mistakes; its example now fits (25 words). The choosing test says a short enabling input, one idea at a time.
- **The settled corrections.** A live-completed My Turn's finished helper follows on the next slide (the skill route had said the opposite). The activity list says what its entries actually carry, counts seven formats in each of its first three sections, and names Free Recall and partner discussion where it named entries that are gone. The evidence file keeps sentence stems and push-back questions as the conditional tools and names the one Synthesise as the discussion route's own beat. A skill lesson's short explanation before its first model and a task lesson's `modelledOn` are words the class reads, in the designer's list and in the reviewer's view of the lesson as the class meets it. The two rules the check held and nothing stated are written where the designer reads them: a skill lesson runs each concept's cycles together in the order it lists them, and a Talk's question is its Stimulus's word for word; the turn-label message carries his maths ruling (the plain words in maths, the move after them elsewhere). A pointer names its real section (in the designer's file and, found by grepping, the maths file); the discussion route's sources sit under it; Karpicke is spelt right; the evidence file is for designing lessons, not PowerPoints; "the existing route" and three sources for entries that are gone come out. The designer's form check keeps the route on the board in whole sentences, said more fully in the script, and the check's message for an empty Teach opens on the sentence the slide lands.
- **Pinned.** `scripts/tests/routes_ledger_pins.json` with `test_routes_ledger_is_kept.py`: all 592 rows where they now live, 69 changed rows each with the decision that changed it (twelve changed first by 7A and the subject files, mapped with their words) and 17 moved under the new headings, five added records (13b in its four places, the reviewer's launch line, the designer's read line, the pointers, the two pointer lines), and the two headings paragraph by paragraph. Decision tests hold every decision and settled item, and two new tests hold the widened check on both sides of each case and the class view's two fields. Thirty-eight pins in 37 rows of the earlier topics, and three of their home records, followed the words they held, each with the decision that moved them (quick checks, success criteria, the rhythm, starters, subject files and worksheets). The mapping is `plans/2026-09-26-routes-mapping.md`.
- **Checked.** CHECKED_LINE
- **Size, honestly.** SIZE_LINE
- **Not done yet.** Untried on a real run. Six of the saved maths lessons would now be sent back to show a good explanation first, as his answer asked; a lesson already running when this release is installed has its design checked again at the adaptation picture step and at review, so it is installed between lessons, never while one is running. 7B still writes decision 2's words into the designer's two launch pointers and the case-first line (its B10), and takes "You can pass" out of the route files (its B6). Release 4 folds the routes' repeated rules, among them the launch fields a task lesson now reads twice. A Do the task whose written explanation carries neither `reasoningWords` nor `rehearsal` (an older class whose connecting words have been faded) is not checked; the reviewer's launch line still is. One dated story stays in a moved paragraph (three science boards, 22 September 2026) because no decision named it; it is already in this log. A discovery Use the learning's `activity` and a bounded attempt's `activity` are words children are given too, and the review view still leaves them out.
"""

CHECKED = ("Every suite passes (Python PYTHON, voice VOICE, builder BUILDER, worksheet WORKSHEET, stick-in STICKIN, "
           "wall WALL, shared SHARED, test TEST). The change scripts, replayed on a clean 4.2.293 copy, reproduce the "
           "tree, the pins and the mapping. The 53 saved designs, as saved, give exactly the faults they gave before (7A's "
           "retired keys and earlier checks stop them first). Stripped of those keys and read by the widened "
           "check alone: six maths skill lessons are newly refused, and each passes once its Practise's launch shows a good "
           "one beside a weak one; a one-line launch with their rounding steps attached as criteria no longer passes. "
           "The history comparison lesson whose criteria list what a good comparison has is refused, as it was before, "
           "until it shows a good one. Every saved "
           "design's review card differs only in the source fingerprints; two task lessons' class views gain their "
           "`modelledOn` lines (49 to 53 strings, 47 to 48).")
SIZE = ("The instruction files are about 2.3 KB larger, not smaller: the lesson designer 1.2 KB (the read line, 13b "
        "twice, the child-facing list), the route files and references a little each way (the stories out, the "
        "pointers in), the activity list and the modelling file smaller. The programs are 2.9 KB larger (the widened "
        "check and its reasons 2.3 KB, the class view 0.6 KB). A lesson on another route that explains now reads the "
        "two sections, about 9 KB and 3 KB, which is what his answer asks. The tests and pins are about 650 KB larger, "
        "601 KB of it the new pin file.")

text = read(LOG)
assert text.count(HEADING) == 1
start = text.index(HEADING)
stories = text.index(STORIES, start)
between = text[start + len(HEADING):stories]
assert between.strip() == "", "the entry's body is already written"
nl = "\r\n" if "\r\n" in text else "\n"
body = BODY.replace("CHECKED_LINE", CHECKED).replace("SIZE_LINE", SIZE)
for placeholder, value in (("PYTHON", "2,337"), ("VOICE", "21"), ("BUILDER", "772"), ("WORKSHEET", "771"),
                           ("STICKIN", "73"), ("WALL", "166"), ("SHARED", "126"), ("TEST", "46")):
    body = body.replace(placeholder, value)
write(LOG, text[:start] + HEADING + nl + nl + body.replace("\n", nl) + text[stories:])
print("LOG_ENTRY_OK")
